name: Project Board Sync

on:
  issues:
    types: [labeled, opened]

jobs:
  add-to-project:
    name: Add Issue to Project Board
    runs-on: ubuntu-latest
    if: >
      contains(github.event.issue.labels.*.name, 'beta-feedback') &&
      (contains(github.event.issue.labels.*.name, 'Critical') || contains(github.event.issue.labels.*.name, 'High'))
    steps:
      - name: Add to Project Board
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
